friend/urls.py
from django.urls import path, include
from . import views
app_name = "friend"

urlpatterns = [
    path('',  views.index, name='index'),
    path('add/',  views.add, name='add'),
    path('delete/<int:id_friendship>',  views.delete_friend, name='del'),

    path('pending/', views.pending, name='pending'),
    path('accept/<int:id_friendship>', views.accept, name='accept'),
    path('refuse/<int:id_friendship>', views.refuse, name='refuse'),
    path('refused/', views.refused, name='refused'),
    path('list/', views.list, name='list'),
]

game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path('', views.game, name="game"),
]

pong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('privacy-policy/', views.privacy_policy),
    path('friend/', include('friend.urls')),
    path('player/', include('player.urls')),
    path('game/', include('game.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friend/models.py
from django.db import models
from player.models import Player

class Friendship(models.Model):
    user = models.ForeignKey(Player, related_name='%(class)s_user1', on_delete=models.CASCADE)
    friend = models.ForeignKey(Player, related_name='%(class)s_player',  on_delete=models.CASCADE)

    status = models.CharField(max_length=10, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'friend')
    
    def __str__(self):
        return self.user.username + ' ' + self.friend.username + ' ' + self.status
    

friend/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .models import Friendship
from django.contrib import messages
from django.db.models import Q
from .models import Player

from django.utils import timezone
# Create your views here.

def index(request):
    return render(request, "friend/index.html")

def add(request):
    if request.method == 'POST':
        you = request.user
        you.last_login = timezone.now()
        you.save()
        if request.POST.get('username') == you.username:
            messages.add_message(request, messages.INFO, "can't add yourself")
            return render(request, "friend/add.html")
        users = Player.objects.filter(username=request.POST.get('username'))
        if len(users) == 0:
            messages.add_message(request, messages.INFO, ("user doesn't exist"))
            return render(request, "friend/add.html")
        new_friend = Friendship.objects.filter(Q(user=you, friend=users[0]) | Q(user=users[0], friend=you))
        if len(new_friend) != 0:
            messages.add_message(request, messages.INFO, ("invitation already sent"))
            return render(request, "friend/add.html")
        new_friend = Friendship(user=you, friend=users[0])
        new_friend.save()
        return render(request, "friend/work.html", {'friend':users[0], 'you':you})
        # Handle the submitted username as needed
        # For example, you can query the User model or process it in other ways
    return render(request, "friend/add.html")
    
def delete_friend(request, id_friendship):
    request = Friendship.objects.get(id=id_friendship)
    request.delete()
    return redirect("friend:list")

def accept(request, id_friendship):
    request = Friendship.objects.get(id=id_friendship)
    request.status = 'accepted'
    request.save()
    return redirect("friend:pending")

def refuse(request, id_friendship):
    request = Friendship.objects.get(id=id_friendship)
    request.status = 'refused'
    request.save()
    return redirect("friend:pending")

def list(request):
    you = request.user
    friends = Friendship.objects.filter(Q(user=you, status='accepted') | Q(friend=you, status='accepted'))
    you.last_login = timezone.now()
    you.save()
    return render(request, "friend/list.html", {'friends':friends, 'you':you})

def pending(request):
    you = request.user
    friends = Friendship.objects.filter(Q(friend=you, status='pending'))
    you.last_login = timezone.now()
    you.save()
    return render(request, "friend/pending.html", {'friends':friends, 'you':you})

def refused(request):
    you = request.user
    friends = Friendship.objects.filter(Q(friend=you, status='refused'))
    you.last_login = timezone.now()
    you.save()
    return render(request, "friend/refused.html", {'friends':friends, 'you':you})

friend/templates/friend/add.html
{% extends 'layout.html' %}

{% block title %}
    Submit Username
{% endblock %}

{% block content %}
<br><br>

<body>
    <h1>Submit Another User's Username</h1>
    <br>
    {% if messages %}
        {% for message in messages %}
            <h2 style="color: red">⚠️{{ message }}⚠️</h2>
        {% endfor %}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <button type="submit">Submit</button>
    </form>
</body>
{% endblock %}

friend/templates/friend/hello.html
hey ca marche

friend/templates/friend/index.html
{% extends 'layout.html' %}

{% block title %}
    FRIENDS
{% endblock %}

{% block content %}
    <br><br>

    <p><a href= "{% url 'friend:add' %}">add friend</a></p>
    <p><a href= "{% url 'friend:list' %}">friend list</a></p>
    <p><a href= "{% url 'friend:pending' %}">pending list</a></p>
    <p><a href= "{% url 'friend:refused' %}">refused list</a></p>
{% endblock %}

friend/templates/friend/list.html
{% extends 'layout.html' %}

{% block title %}
    Friend list
{% endblock %}

{% block content %}
<br><br>
    {% for elem in friends %}
        <p>
        {% if elem.user.username == you.username %}
            <img src="{{ elem.friend.profile_picture.url }}" width="50" height="40"/>
            {{elem.friend.username}}
        {% else %}
            <img src="{{ elem.user.profile_picture.url }}" width="50" height="40"/>
            {{elem.user.username}}
        {% endif %}
        | <a href= "{% url 'friend:del' elem.id %}">delete</a></p>
    {% endfor %}
{% endblock %}

friend/templates/friend/pending.html
{% extends 'layout.html' %}

{% block title %}
    Pending list
{% endblock %}

{% block content %}
<br><br>
    {% for elem in friends %}

    <p>{{elem.user.username}}
    | 
    <a href= "{% url 'friend:accept' elem.id %}">accept</a>
    / 
    <a href= "{% url 'friend:refuse' elem.id %}">refuse</a></p>
    {% endfor %}
{% endblock %}

friend/templates/friend/refused.html
{% extends 'layout.html' %}

{% block title %}
    Refused List
{% endblock %}

{% block content %}
    {% for elem in friends %}

        <p>{{elem.user.username}}
        | 
        <a href= "{% url 'friend:accept' elem.id %}">accept</a>
    {% endfor %}
{% endblock %}

friend/templates/friend/work.html
work<br>

{% for elem in n %}
    {{elem}}

{% endfor %}

<br>

{{friend}} | {{you}}