game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path('', views.game, name="game"),
]

player/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "player"

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('success/', views.success_view, name='success'),
    path('login/', views.login_view, name="login"),
    path('otp/', views.otp_view, name="otp"),
    path('display_qr/', views.display_qr_view, name="display_qr"),
    path('account/', views.account_view, name="account"),
    path('auth/42/callback/', views.auth_42_callback, name='auth_42_callback'),
    path('logout/', views.logout_view, name='logout'),
    path('update/', views.update, name='update'),
    path('update/password', views.update_password, name='update_password'),
]

pong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('privacy-policy/', views.privacy_policy),
    path('friend/', include('friend.urls')),
    path('player/', include('player.urls')),
    path('game/', include('game.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

player/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Player(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, default='profile_pictures/fallback.png')
    rank = models.IntegerField(default=1000)
    phone_number = PhoneNumberField(blank=True, null=True)
    win = models.IntegerField(default=0)
    lose = models.IntegerField(default=0)
    nickname = models.CharField(blank=True, null=True, max_length=30)
    def __str__(self):
        return self.username
    

player/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from phonenumbers.phonenumberutil import is_valid_number, parse
from .models import Player

class ChangePasswordForm(SetPasswordForm):
    class Meta:
        model = Player
        fields = ['new_password1', 'new_password2']

class UpdateForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['nickname', 'email', 'phone_number']

class RegisterForm(UserCreationForm):
    email = forms.EmailField(
        label='Email Address',
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    phone_number = forms.CharField(
        label='Phone Number (optional)',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Player
        fields = ['username', 'email', 'phone_number', 'password1', 'password2']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if phone_number:
            try:
                parsed_number = parse(phone_number, None)

                if not is_valid_number(parsed_number):
                    raise forms.ValidationError("Invalid phone number")
            except Exception:
                raise forms.ValidationError("Invalid phone number")
        return phone_number

    def save(self, commit=True):
        user = super().save(commit=False)
        user.phone_number = self.cleaned_data['phone_number']
        if commit:
            user.save()
        return user


class PhoneForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['phone_number']

player/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from .otp import send_otp, create_otp_code, create_qr_code
from .forms import RegisterForm, PhoneForm, ChangePasswordForm, UpdateForm
from .models import Player
import pyotp
import requests
from django.conf import settings
from django.contrib import messages

def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            user.nickname = user.username
            login(request, user)
            return redirect(f'/player/success/?username={user.username}')
    else:
        form = RegisterForm()
    return render(request, 'player/register.html', {'form': form})

def success_view(request):
    username = request.GET.get('username')
    user = get_object_or_404(Player, username=username)
    context = {
        'user': user,
        'phone_number': user.phone_number,
    }
    return render(request, 'player/success.html', context)

def login_view(request):
    if request.method == "POST":
        if 'login' in request.POST:
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                user = form.get_user()

                otp_method = request.POST.get('otp_method')
                totp = pyotp.TOTP(pyotp.random_base32(), interval=60)

                request.session['username'] = user.username
                request.session['otp_secret_key'] = totp.secret
                request.session['otp_valid_date'] = (datetime.now() + timedelta(minutes=1)).isoformat()

                if  otp_method == 'sms':
                    send_otp(request, totp, method='sms')
                elif otp_method == 'email':
                    send_otp(request, totp, method='email')
                elif otp_method == 'no':
                    connected_user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
                    if connected_user is not None:
                        #return render(request, 'player/weird.html', {'username': request.POST.get('username'), 'password': request.POST.get('password')})
                        login(request, connected_user)
                        return redirect(f'/player/account/?username={user.username}')                  
                    else:
                        form = AuthenticationForm()
                        return render(request, 'player/login.html', {"form": form})
                return redirect('/player/otp/')
            #elif 'login_with_42' in request.POST: 
             #   redirect_uri = settings.FT42_REDIRECT_URI
              #  client_id = settings.FT42_CLIENT_ID
               # auth_url = f"https://api.intra.42.fr/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
                #return redirect(auth_url)
    else:
        form = AuthenticationForm()
    return render(request, 'player/login.html', {"form": form})

def otp_view(request):
    if request.method == "POST":
        #if 'Resend_code':
        #    send_otp(request, totp, method='sms')

        user_otp = request.POST.get('otp')
        otp_secret_key = request.session.get('otp_secret_key')
        otp_valid_date = request.session.get('otp_valid_date')

        if otp_secret_key and otp_valid_date:
            valid_until = datetime.fromisoformat(otp_valid_date)

            if valid_until > datetime.now():
                totp = pyotp.TOTP(otp_secret_key, interval=60)
                if totp.verify(user_otp):
                    username = request.session.get('username')
                    user = get_object_or_404(Player, username=username)
                    login(request, user)

                    del request.session['otp_secret_key']
                    del request.session['otp_valid_date']
                    del request.session['username']
                    if not user.nickname:
                        user.nickname = user.username
                        user.save()
                    return redirect(f'/player/account/?username={user.username}')
            else:
                return render(request, 'player/otp.html', {'error': 'OTP has expired'})
        return render(request, 'player/otp.html', {'error': 'Invalid OTP'})
    return render(request, 'player/otp.html')


def display_qr_view(request):
    totp_secret_key = request.session.get('otp_secret_key')
    if not totp_secret_key:
        return redirect('/player/account/')
    totp = pyotp.TOTP(totp_secret_key, interval=60)
    qr_data = create_qr_code(request, totp)
    return render(request, 'player/display_qr.html', {'qr_data': qr_data})


@login_required
def account_view(request):
    user = request.user
    player = get_object_or_404(Player, username=user.username)

    if request.method == 'POST':
        form = PhoneForm(request.POST, instance=player)
        if form.is_valid():
            form.save()
            if not user.nickname:
                user.nickname = user.username
                user.save()
            return redirect(f'/player/account/?username={user.username}')
    else:
        form = PhoneForm(instance=player)

    return render(request, 'player/account.html', {'form': form})


def auth_42_callback(request):
    code = request.GET.get('code')
    if not code:
        return redirect('/player/login/')

    token_url = 'https://api.intra.42.fr/oauth/token'
    data = {
        'grant_type': 'authorization_code',
        'client_id': settings.FT42_CLIENT_ID,
        'client_secret': settings.FT42_CLIENT_SECRET,
        'code': code,
        'redirect_uri': settings.FT42_REDIRECT_URI,
    }

    print('############################')
    print('client_id : ' + settings.FT42_CLIENT_ID)
    print('client_secret : ' + settings.FT42_CLIENT_SECRET)
    print('code : ' + code)
    print('redirect_uri : ' + settings.FT42_REDIRECT_URI)
    print('token_url : ' + token_url)

    response = requests.post(token_url, data=data)
    if response.status_code != 200:
        return redirect('/player/login/')

    token_info = response.json()
    access_token = token_info.get('access_token')
    if not access_token:
        return redirect('/player/login/')

    user_info_response = requests.get(
        'https://api.intra.42.fr/v2/me',
        headers={'Authorization': f'Bearer {access_token}'}
    )
    if user_info_response.status_code != 200:
        return redirect('/player/login/')

    user_info = user_info_response.json()
    username = user_info.get('login')
    email = user_info.get('email')

    print('\n')
    print('login : ' + user_info.get('login'))
    print('email : ' + user_info.get('email'))
    print('last_name : ' + user_info.get('last_name'))
    print('############################')

    user, created = Player.objects.get_or_create(
        username=username,
        defaults={'email': email}
    )

    login(request, user)
    if not user.nickname:
        user.nickname = user.username
        user.save()
    return redirect(f'/player/account/?username={user.username}')


@login_required
def logout_view(request):
    logout(request)
    return redirect(f'/player/login/')


@login_required
def update(request):
    user = request.user

    if request.method == 'POST':
        form = UpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect(f'/player/account/?username={user.username}')
    else:
        form = UpdateForm(instance=user)
    return render(request, 'player/update.html', {'form': form})

@login_required
def update_password(request):
    user = request.user
    if request.method == 'POST':
        return redirect(f'/player/account/?username={user.username}')
    else:
        form = ChangePasswordForm(user)
        return render(request, 'player/update_password.html', {"form": form})

player/templates/player/account.html
{% extends 'layout.html' %}

{% block title %}
    MY ACCOUNT
{% endblock %}

{% block content %}
<br>
<h1>MY ACCOUNT</h1>
<br>
    <h2>Infos</h2>
        <br>
        <img src="transcendence\profile_pictures\SNIP 2024-04-13.png">
        <p>username = {{ user.username }}</p>
        <p>nickname = {{ user.nickname }}</p>
        <p>email = {{ user.email }}</p>
        <p>password = {{ user.password }}</p>
        <p>phone = {{ user.phone_number }}</p>
        <br>
        <a href="{% url 'player:update' %}">Edit info</a> <br>
        <a href="{% url 'player:update_password' %}">Change password</a>
        <br>
        <br>
    <form href="/player/logout" method="post">
        {% csrf_token %}
        <button type="submit">Log out</button>
    </form>
{% endblock %}

player/templates/player/display_qr.html
{% extends 'layout.html' %}

{% block title %}
    Scan QR Code
{% endblock %}

{% block content %}
    <br><br>
    <h1>Scan the QR Code with your Authenticator App</h1>
    <br>
    <img src="data:image/png;base64,{{ qr_data }}" alt="QR Code">

{% endblock %}

player/templates/player/login.html
{% extends 'layout.html' %}

{% block title %}
    Player Login
{% endblock %}

{% block content %}
    <br>
    <h1>Player Login</h1>
    <br>

    <form class="form-width-validation" action="/player/login/" method="post">
        {% csrf_token %}
        {{ form }}
        <br><br>
        <label>
            <input type="radio" name="otp_method" value="email" checked> Receive OTP via Email
        </label>
        <br>
        <label>
            <input type="radio" name="otp_method" value="qr"> Use QR Code
        </label>
        <br>
        <label>
            <input type="radio" name="otp_method" value="no"> Don't use 2FA
        </label>
        <br><br>

        <button type="submit" name="login">Log in</button>
    </form>
    <br><br>
    <a href="https://api.intra.42.fr/oauth/authorize?client_id=u-s4t2ud-16025b9787666ade4d4f1d6dea5934752712328ed62f01905c7627b9d195d996&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fplayer%2Fauth%2F42%2Fcallback%2F&response_type=code">Log in with 42</a>

{% endblock %}

player/templates/player/otp.html
{% extends 'layout.html' %}

{% block title %}
    OTP
{% endblock %}

{% block content %}
<br>
    <h1>OTP</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="otp">OTP:</label>
            <input class="form" type="text" name="otp" required>
        </div>
        <button type="submit">Confirm</button>
    </form>
    <form action="" method="post">
        {% csrf_token %}
        <button action="Resend_code">Resend code</button>
    </form>
    {% if error %}
        <br>
        <p style="color: red;">{{ error }}</p>
    {% endif %}
    </form>
    {% endblock %}

player/templates/player/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
<br>

    <h1>Register a New User</h1>
        <!-- other form fields -->
    <form class="form-width-validation" action="/player/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <br><br>
        <label>
            <input type="checkbox" name="consent" required> I agree to the <a href="/privacy-policy">privacy policy</a>.
        </label>
        <br><br>
        <button>Submit</button>
    </form>
    
{% endblock %}

player/templates/player/success.html
{% extends 'layout.html' %}

{% block title %}
    Success
{% endblock %}

{% block content %}
<br>
    <h2>Registration successful!</h2>
<br>

    <p>Thank you for registering.</p>
    <p>username = {{ user.username }}</p>
    <p>email = {{ user.email }}</p>
    <p>password = {{ user.password }}</p>
    <p>phone = {{ user.phone_number }}</p>

{% endblock %}

player/templates/player/update.html
{% extends 'layout.html' %}

{% block title %}
    Player Update
{% endblock %}

{% block content %}
    <br>
    <h1>Player Update</h1>
    <br>
    {% if messages %}
    {% for message in messages %}
        <h2 style="color: red">⚠️{{ message }}⚠️</h2>
    {% endfor %}
    {% endif %}
    <br>
    <form method="post" action="/player/update/">
        {% csrf_token %}
        {{ form }}

        <button type="submit" name="login">Update</button>
    </form>
    <br><br>
{% endblock %}

player/templates/player/update_password.html
{% extends 'layout.html' %}

{% block title %}
    Change password
{% endblock %}
{% block content %}
<br>
<h1>Update Password</h1>
<br>

<br><br>
<form action="/player/account/?username="{{user.username}} method="post">
    {% csrf_token %}
    
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}